name: CI

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Java 12 compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@master
        with:
          java-version: 12
      - run: mvn -f pom.xml -DskipTests=true clean compile
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@master
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 12
      uses: actions/setup-java@master
      with:
        java-version: 12
    - name: Build and test project
      run: mvn -f pom.xml -DskipTests=true clean package
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@master
      with:
        name: artifact
        path: target/HanaAppContainer.war
